FROM    scratch
LABEL   description="Image containing set of qbitwiki files" \
        maintainer="marcin.narloch@qbituniverse.com"

COPY    commands /qbitwiki/commands
COPY    scripts /qbitwiki/scripts
COPY    templates /qbitwiki/templates