pool:
  vmImage: 'ubuntu-latest'

trigger:
- master

pr: none

steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: DockerHub
    repository: qbituniverse/qbitwiki
    Dockerfile: '.cicd/docker/Dockerfile-qbitwiki'
    buildContext: ''
    tags: latest
